#NumPy

https://numpy.org

In [2]:
# Importando o numpy
import numpy as dsa

In [3]:
dsa.__version__

'1.23.5'

# Criando arrays NumPy

In [4]:
# Array criado a partir de uma lista Python
arr1 = dsa.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [5]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [6]:
# Um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho
type(arr1)

numpy.ndarray

In [7]:
# Verificando o formato do array
arr1.shape

(9,)

# Indexação em arrays NumPy

In [8]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [9]:
# Imprimindo um elemento especifico no array
arr1[4]

48

In [10]:
#indexação
arr1[1:4]

array([21, 32, 43])

In [11]:
# indexação
arr1[1:4+1]

array([21, 32, 43, 48])

In [12]:
# cria uma lista de indices
indices = [1, 2, 5, 6]

In [13]:
# Imprimnido os elementos dos indices
arr1[indices]

array([21, 32, 15, 76])

In [14]:
# Cria uma mascara booleana para os elementos pares
mask = (arr1 % 2 == 0)

In [15]:
arr1[mask]

array([10, 32, 48, 76])

In [16]:
# Alterando um elemento do array
arr1[0] = 100

In [17]:
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [18]:
# não é possivel incluir elemento de outro tipo
try:
    arr1[0] = 'Novo elemento'
except:
    print("Operação não permiitida")

Operação não permiitida


In [19]:
arr1[0] = 'novo elemento'

ValueError: invalid literal for int() with base 10: 'novo elemento'

# Funções NumPy

In [21]:
# A função array() cria um array NumPy
arr2 = dsa.array([1, 2, 3, 4, 5])

In [22]:
print(arr2)

[1 2 3 4 5]


In [23]:
# Verificando o tipo do objeto
type(arr2)

numpy.ndarray

In [24]:
# Digite . e pressione a tecla Tab no seu teclado para visualizar os metodos disponiveis em objetos NumPy
arr2

array([1, 2, 3, 4, 5])

In [25]:
# Usando metodos do array NumPy
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [27]:
arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [28]:
dsa

<module 'numpy' from 'C:\\Users\\Borges\\AppData\\Roaming\\Python\\Python39\\site-packages\\numpy\\__init__.py'>

In [29]:
arr3 = dsa.arange(0, 50, 5)

In [30]:
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [31]:
# Verificando o tipo do objeto
type(arr3)

numpy.ndarray

In [32]:
# Formato do array
dsa.shape(arr3)

(10,)

In [33]:
print(arr3.dtype)

int32


In [34]:
# Cria um array preenchido com zeros
arr4 = dsa.zeros(10)

In [35]:
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [36]:
# Retorna 1 nas posições em diagonal e 0 no restante
arr5 = dsa.eye(3)

In [37]:
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
# Os valores passados como parametro, formam uma diagonal
arr6 = dsa.diag(dsa.array([1,2,3,4]))

In [39]:
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [40]:
# array de valores booleanos
arr7 = dsa.array([True, False, True, False])

In [41]:
print(arr7)

[ True False  True False]


In [43]:
# Array de strings
arr8 = dsa.array(['Linguagem Python', 'Linguagem R', 'Linguagem Julia'])

In [45]:
print(arr8)

['Linguagem Python' 'Linguagem R' 'Linguagem Julia']


A função linspace() do NumPy é usada para criar uma sequencia de numeros igualmente dentro de um intervalo especifico. Essa função é amplamente utilizada em programação cientifica e matematica para gerar arrays de numeros para diverso fins, como graficos, calculos e simulações.

Metodo  linspace (linearly space vector) retorna um numero de valores igualmente distribuidos no intervalo especificado.

In [46]:
print(dsa.linspace(0,10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [47]:
print(dsa.linspace(0,10,15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


A função logspace() do NumPy é usada para criar uma sequencia de numeros igualmente espaçados em escala logaritma  dentro de um intervalo especifico. Essa função é amplamente utilizada em programação cientifica e matematica para gerar arrays de numeros para diversos fins, como graficos, calculos e simulações.

In [49]:
print(dsa.logspace(0,5,10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]
