#NumPy

https://numpy.org

In [50]:
# Importando o numpy
import numpy as dsa

In [51]:
dsa.__version__

'1.23.5'

# Criando arrays NumPy

In [52]:
# Array criado a partir de uma lista Python
arr1 = dsa.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [53]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [54]:
# Um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho
type(arr1)

numpy.ndarray

In [55]:
# Verificando o formato do array
arr1.shape

(9,)

# Indexação em arrays NumPy

In [56]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [57]:
# Imprimindo um elemento especifico no array
arr1[4]

48

In [58]:
#indexação
arr1[1:4]

array([21, 32, 43])

In [59]:
# indexação
arr1[1:4+1]

array([21, 32, 43, 48])

In [60]:
# cria uma lista de indices
indices = [1, 2, 5, 6]

In [61]:
# Imprimnido os elementos dos indices
arr1[indices]

array([21, 32, 15, 76])

In [62]:
# Cria uma mascara booleana para os elementos pares
mask = (arr1 % 2 == 0)

In [63]:
arr1[mask]

array([10, 32, 48, 76])

In [64]:
# Alterando um elemento do array
arr1[0] = 100

In [65]:
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [66]:
# não é possivel incluir elemento de outro tipo
try:
    arr1[0] = 'Novo elemento'
except:
    print("Operação não permiitida")

Operação não permiitida


In [67]:
arr1[0] = 'novo elemento'

ValueError: invalid literal for int() with base 10: 'novo elemento'

# Funções NumPy

In [ ]:
# A função array() cria um array NumPy
arr2 = dsa.array([1, 2, 3, 4, 5])

In [ ]:
print(arr2)

[1 2 3 4 5]


In [ ]:
# Verificando o tipo do objeto
type(arr2)

numpy.ndarray

In [ ]:
# Digite . e pressione a tecla Tab no seu teclado para visualizar os metodos disponiveis em objetos NumPy
arr2

array([1, 2, 3, 4, 5])

In [ ]:
# Usando metodos do array NumPy
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [ ]:
arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [ ]:
dsa

<module 'numpy' from 'C:\\Users\\Borges\\AppData\\Roaming\\Python\\Python39\\site-packages\\numpy\\__init__.py'>

In [ ]:
arr3 = dsa.arange(0, 50, 5)

In [ ]:
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [ ]:
# Verificando o tipo do objeto
type(arr3)

numpy.ndarray

In [ ]:
# Formato do array
dsa.shape(arr3)

(10,)

In [ ]:
print(arr3.dtype)

int32


In [ ]:
# Cria um array preenchido com zeros
arr4 = dsa.zeros(10)

In [ ]:
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Retorna 1 nas posições em diagonal e 0 no restante
arr5 = dsa.eye(3)

In [ ]:
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Os valores passados como parametro, formam uma diagonal
arr6 = dsa.diag(dsa.array([1,2,3,4]))

In [ ]:
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
# array de valores booleanos
arr7 = dsa.array([True, False, True, False])

In [ ]:
print(arr7)

[ True False  True False]


In [ ]:
# Array de strings
arr8 = dsa.array(['Linguagem Python', 'Linguagem R', 'Linguagem Julia'])

In [ ]:
print(arr8)

['Linguagem Python' 'Linguagem R' 'Linguagem Julia']


A função linspace() do NumPy é usada para criar uma sequencia de numeros igualmente dentro de um intervalo especifico. Essa função é amplamente utilizada em programação cientifica e matematica para gerar arrays de numeros para diverso fins, como graficos, calculos e simulações.

Metodo  linspace (linearly space vector) retorna um numero de valores igualmente distribuidos no intervalo especificado.

In [ ]:
print(dsa.linspace(0,10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [ ]:
print(dsa.linspace(0,10,15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


A função logspace() do NumPy é usada para criar uma sequencia de numeros igualmente espaçados em escala logaritma  dentro de um intervalo especifico. Essa função é amplamente utilizada em programação cientifica e matematica para gerar arrays de numeros para diversos fins, como graficos, calculos e simulações.

In [ ]:
print(dsa.logspace(0,5,10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


Manipulando Matrizes

In [68]:
# Criando uma matriz
arr9 = dsa.array([[1,2,3], [4,5,6]])

In [69]:
type(arr9)

numpy.ndarray

In [70]:
print(arr9)

[[1 2 3]
 [4 5 6]]


In [71]:
print(arr9.shape)

(2, 3)


In [72]:
# Criando uma matriz 2x3 apenas com numeros "1"
# Isso é possivel utilizando a função do numpy "ones"
arr10 = dsa.ones((2,3))

In [73]:
print(arr10)

[[1. 1. 1.]
 [1. 1. 1.]]


In [74]:
# Lista de listas
lista = [[13,81,22], [0,34,59], [21,48,94]]

In [75]:
# A função matrix cria uma matrix a partir de uma lista de listas
arr11 = dsa.matrix(lista)

In [76]:
type(arr11)

numpy.matrix

In [77]:
print(arr11)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]


In [78]:
# Formato de matriz
dsa.shape(arr11)

(3, 3)

In [79]:
# Tamanho da matriz
arr11.size

9

In [80]:
print(arr11.dtype)

int32


In [81]:
print(arr11)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]


In [82]:
# Indexação da matriz
arr11[2,1]

48

In [83]:
# Indexação da matriz
arr11[0:2,2]

matrix([[22],
        [59]])

In [84]:
arr11[1,]

matrix([[ 0, 34, 59]])

In [85]:
# Alterando um elemento da matriz
arr11[1,0] = 100

In [86]:
print(arr11)

[[ 13  81  22]
 [100  34  59]
 [ 21  48  94]]


In [87]:
x = dsa.array([1,2]) # Numpy decide o tipo dos dado
y = dsa.array([1.0,2.0]) # Numpy decide o tipo dos dado
z = dsa.array([1,2], dtype = dsa.float64) # Forçamos um tipo de dados em particular

In [88]:
print(x.dtype, y.dtype, z.dtype)

int32 float64 float64


In [89]:
# Neste caso realizamos a alteração do tipo da lista para um na criação.
arr12 = dsa.array([[24,76,82,14], [47,35,89,2]], dtype = float)

In [91]:
print(arr12)

[[24. 76. 82. 14.]
 [47. 35. 89.  2.]]


O itemsize de uma array numpy é atributo que retorna o tamanho em bytes de cada elemento do array. Em outras palavras, o itemsize representa o numero de bytes necessarios para armazenar cada valor do array numpy.

In [92]:
arr12.itemsize

8

In [93]:
arr12.nbytes

64

In [94]:
arr12.ndim

2