#NumPy

https://numpy.org

In [1]:
# Importando o numpy
import numpy as dsa

In [2]:
dsa.__version__

'1.23.5'

# Criando arrays NumPy

In [9]:
# Array criado a partir de uma lista Python
arr1 = dsa.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [10]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [11]:
# Um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho
type(arr1)

numpy.ndarray

In [12]:
# Verificando o formato do array
arr1.shape

(9,)

# Indexação em arrays NumPy

In [13]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [14]:
# Imprimindo um elemento especifico no array
arr1[4]

48

In [16]:
#indexação
arr1[1:4]

array([21, 32, 43])

In [17]:
# indexação
arr1[1:4+1]

array([21, 32, 43, 48])

In [18]:
# cria uma lista de indices
indices = [1, 2, 5, 6]

In [19]:
# Imprimnido os elementos dos indices
arr1[indices]

array([21, 32, 15, 76])

In [20]:
# Cria uma mascara booleana para os elementos pares
mask = (arr1 % 2 == 0)

In [21]:
arr1[mask]

array([10, 32, 48, 76])

In [22]:
# Alterando um elemento do array
arr1[0] = 100

In [23]:
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [24]:
# não é possivel incluir elemento de outro tipo
try:
    arr1[0] = 'Novo elemento'
except:
    print("Operação não permiitida")

Operação não permiitida


In [25]:
arr1[0] = 'novo elemento'

ValueError: invalid literal for int() with base 10: 'novo elemento'